spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - client
      - mysql
      - security
      - cookie
      - log

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger