spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - client-dev
      - mysql-dev
      - security-dev
      - cookie-dev
      - log-dev

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger