spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - client-prod
      - mysql-prod
      - security-prod
      - cookie-prod
      - log-prod

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger