spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - client-local
      - mysql-local
      - security-local
      - cookie-local
      - log-local

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger