spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - flyway
      - mysql
      - batch
      - security
      - client-jsoup
      - client-thread
      - client-wifi
      - slack