spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - flyway-local
      - mysql-local
      - batch-local
      - security-local
      - client-jsoup-local
      - client-thread-local
      - client-wifi
      - slack-local

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      wifi:
        obs: DEBUG