spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - flyway-prod
      - mysql-prod
      - batch-prod
      - security-prod
      - client-jsoup-prod
      - client-thread-prod
      - client-wifi
      - slack