name: Gradle-Test

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  gradle-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.6.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test --warning-mode=all --stacktrace

      - name: Add Unit Test Results to PR
        uses: mikepenz/action-junit-report@v3.8.0
        if: always()
        with:
          report_paths: build/test-results/test/TEST-*.xml

      - name: Add Jacoco Test coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50