name: Gradle-Test

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  gradle-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.6.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Test with Gradle
        run: ./gradlew :app:test --warning-mode=all --stacktrace

      - name: Add Unit Test Results to PR
        uses: mikepenz/action-junit-report@v3.8.0
        if: always()
        with:
          report_paths: app/build/test-results/test/TEST-*.xml

      - name: Add Jacoco Test coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50